coverage:
  ignore:
  - bin/.*
  - config/.*
  status:
    patch:
      default:
        target: 100
    changes:
      default:
        branches:
        - master
    project:
      default:
        target: auto
